export const ADD_NEW_TASK = "ADD_NEW_TASK"
export const SORT_TASK = "SORT_TASK"
export const REMOVE_TASK = "REMOVE_TASK"
export const EDIT_TASK = "EDIT_TASK"
export const TOGGLE_STATUS = "TOGGLE_STATUS"
export const INITIAL_DATA = "INITIAL_DATA"
