const ADD_NEW_TASK = "ADD_NEW_TASK"
const SORT_TASK = "SORT_TASK"
const REMOVE_TASK = "REMOVE_TASK"
const EDIT_TASK = "EDIT_TASK"
const TOGGLE_STATUS = "TOGGLE_STATUS"


module.exports = {
    ADD_NEW_TASK,
    SORT_TASK,
    REMOVE_TASK,
    EDIT_TASK,
    TOGGLE_STATUS
}
